{% set name = "xsimd" %}
{% set version = "11.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/xsimd/archive/{{ version }}.tar.gz
  sha256: aa54dba8daade472656eba0d27154f072fec06ee3831aefcac69a5f6c7dbbae7

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/xsimd/xsimd.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xsimd\xsimd.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xsimd\xsimdConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\xsimd\xsimdConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xsimd
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ Wrappers for SIMD Intrinsices
  description: High-level APIs for SIMD operations
  doc_url: httpis://xsimd.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xsimd

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
