{% set name = "xsimd" %}
{% set version = "6.0.0" %}
{% set sha256 = "1243b0076e842214c9aca3c33ab6073a667ae401760e665ba265f3ad3c36b871" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xsimd/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/xsimd/xsimd.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xsimd/xsimdConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xsimd\xsimd.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xsimdConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xsimdConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xsimd
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ Wrappers for SIMD Intrinsices'
  description: 'High-level APIs for SIMD operations'
  doc_url: http://xsimd.readthedocs.io
  dev_url: https://github.com/QuantStack/xsimd

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
