schema_version: 1

context:
  name: xsimd
  version: 13.2.0
  library_prefix: ${{ "${PREFIX}" if unix else "%LIBRARY_PREFIX%" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/xtensor-stack/xsimd/archive/${{ version }}.tar.gz
  sha256: edd8cd3d548c185adc70321c53c36df41abe64c1fe2c67bc6d93c3ecda82447a

build:
  number: 1
  script:
    - cmake -G "Ninja" -B build/ -D CMAKE_INSTALL_PREFIX=${{ library_prefix }} -D CMAKE_INSTALL_LIBDIR="lib" -D BUILD_TESTS=OFF
    - cmake --build build/
    - cmake --install build/

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - "xsimd/xsimd.hpp"
      files:
        - if: unix
          then:
            - share/cmake/xsimd/xsimdConfig.cmake
            - share/cmake/xsimd/xsimdConfigVersion.cmake
          else:
            - Library/share/cmake/xsimd/xsimdConfig.cmake
            - Library/share/cmake/xsimd/xsimdConfigVersion.cmake

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: C++ Wrappers for SIMD Intrinsices
  description: High-level APIs for SIMD operations
  homepage: https://github.com/xtensor-stack/xsimd
  repository: https://github.com/xtensor-stack/xsimd
  documentation: httpis://xsimd.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
