schema_version: 1

context:
  name: xsimd
  version: 14.1.0
  library_prefix: ${{ "${PREFIX}" if unix else "%LIBRARY_PREFIX%" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/xtensor-stack/xsimd/archive/${{ version }}.tar.gz
  sha256: 8da77b66214e73565f6111ba494322c853552b7b40cff69779b42e2100eed16f

build:
  number: 0
  script:
    - cmake -G "Ninja" -B build/ -D CMAKE_INSTALL_PREFIX=${{ library_prefix }} -D CMAKE_INSTALL_LIBDIR="lib" -D BUILD_TESTS=OFF
    - cmake --build build/
    - cmake --install build/

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - "xsimd/xsimd.hpp"
      files:
        - ${{ "Library/" if win }}share/cmake/xsimd/xsimdConfig.cmake
        - ${{ "Library/" if win }}share/cmake/xsimd/xsimdConfigVersion.cmake

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: C++ Wrappers for SIMD Intrinsices
  description: High-level APIs for SIMD operations
  homepage: https://github.com/xtensor-stack/xsimd
  repository: https://github.com/xtensor-stack/xsimd
  documentation: httpis://xsimd.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - davidbrochart
    - conda-forge/xtensor
